<?php
/**
 * Helper for create a invoice.
 *
 * @author     Alessio Catania
 * @since      1.0.7
 * @package    Wubtitle\Utils
 */

namespace Wubtitle\Utils;

/**
 * Vimeo Helpers
 *
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
class VimeoHelper {
	/**
	 * Return languages array.
	 *
	 * @return array<string>
	 */
	public function get_languages() {
		$languages = array(
			'af'    => __( 'Afrikaans', 'wubtitle' ),
			'sq'    => __( 'Albanian', 'wubtitle' ),
			'ar-AE' => __( 'Arabic (U.A.E.)', 'wubtitle' ),
			'ar-BH' => __( 'Arabic (Bahrain)', 'wubtitle' ),
			'ar-DZ' => __( 'Arabic (Algeria)', 'wubtitle' ),
			'ar-EG' => __( 'Arabic (Egypt)', 'wubtitle' ),
			'ar-IQ' => __( 'Arabic (Iraq)', 'wubtitle' ),
			'ar-JO' => __( 'Arabic (Jordan)', 'wubtitle' ),
			'ar-KW' => __( 'Arabic (Kuwait)', 'wubtitle' ),
			'ar-LB' => __( 'Arabic (Lebanon)', 'wubtitle' ),
			'ar-LY' => __( 'Arabic (Libya)', 'wubtitle' ),
			'ar-MA' => __( 'Arabic (Morocco)', 'wubtitle' ),
			'ar-OM' => __( 'Arabic (Oman)', 'wubtitle' ),
			'ar-QA' => __( 'Arabic (Qatar)', 'wubtitle' ),
			'ar-SA' => __( 'Arabic (Saudi Arabia)', 'wubtitle' ),
			'ar-SY' => __( 'Arabic (Syria)', 'wubtitle' ),
			'ar-TN' => __( 'Arabic (Tunisia)', 'wubtitle' ),
			'ar-YE' => __( 'Arabic (Yemen)', 'wubtitle' ),
			'eu'    => __( 'Basque', 'wubtitle' ),
			'be'    => __( 'Belarusian', 'wubtitle' ),
			'bg'    => __( 'Bulgarian', 'wubtitle' ),
			'ca'    => __( 'Catalan', 'wubtitle' ),
			'hr'    => __( 'Croatian', 'wubtitle' ),
			'zh-CN' => __( 'Chinese (PRC)', 'wubtitle' ),
			'zh-HK' => __( 'Chinese (Hong Kong)', 'wubtitle' ),
			'zh-SG' => __( 'Chinese (Singapore)', 'wubtitle' ),
			'zh-TW' => __( 'Chinese (Taiwan)', 'wubtitle' ),
			'cs'    => __( 'Czech', 'wubtitle' ),
			'da'    => __( 'Danish', 'wubtitle' ),
			'nl'    => __( 'Dutch (Standard)', 'wubtitle' ),
			'nl-BE' => __( 'Dutch (Belgium)', 'wubtitle' ),
			'en'    => __( 'English', 'wubtitle' ),
			'en-AU' => __( 'English (Australia)', 'wubtitle' ),
			'en-BZ' => __( 'English (Belize)', 'wubtitle' ),
			'en-CA' => __( 'English (Canada)', 'wubtitle' ),
			'en-GB' => __( 'English (United Kingdom)', 'wubtitle' ),
			'en-IE' => __( 'English (Ireland)', 'wubtitle' ),
			'en-JM' => __( 'English (Jamaica)', 'wubtitle' ),
			'en-NZ' => __( 'English (New Zealand)', 'wubtitle' ),
			'en-TT' => __( 'English (Trinidad)', 'wubtitle' ),
			'en-US' => __( 'English (United States)', 'wubtitle' ),
			'en-ZA' => __( 'English (South Africa)', 'wubtitle' ),
			'et'    => __( 'Estonian', 'wubtitle' ),
			'fa'    => __( 'Farsi', 'wubtitle' ),
			'fi'    => __( 'Finnish', 'wubtitle' ),
			'fo'    => __( 'Faeroese', 'wubtitle' ),
			'fr'    => __( 'French (Standard)', 'wubtitle' ),
			'fr-BE' => __( 'French (Belgium)', 'wubtitle' ),
			'fr-CA' => __( 'French (Canada)', 'wubtitle' ),
			'fr-CH' => __( 'French (Switzerland)', 'wubtitle' ),
			'fr-LU' => __( 'French (Luxembourg)', 'wubtitle' ),
			'gd'    => __( 'Gaelic (Scotland)', 'wubtitle' ),
			'de'    => __( 'German (Standard)', 'wubtitle' ),
			'de-AT' => __( 'German (Austria)', 'wubtitle' ),
			'de-CH' => __( 'German (Switzerland)', 'wubtitle' ),
			'de-LI' => __( 'German (Liechtenstein)', 'wubtitle' ),
			'de-LU' => __( 'German (Luxembourg)', 'wubtitle' ),
			'el'    => __( 'Greek', 'wubtitle' ),
			'ga'    => __( 'Irish', 'wubtitle' ),
			'he'    => __( 'Hebrew', 'wubtitle' ),
			'hi'    => __( 'Hindi', 'wubtitle' ),
			'hu'    => __( 'Hungarian', 'wubtitle' ),
			'id'    => __( 'Indonesian', 'wubtitle' ),
			'is'    => __( 'Icelandic', 'wubtitle' ),
			'it'    => __( 'Italian (Standard)', 'wubtitle' ),
			'it-CH' => __( 'Italian (Switzerland)', 'wubtitle' ),
			'ja'    => __( 'Japanese', 'wubtitle' ),
			'ko'    => __( 'Korean (Johab)', 'wubtitle' ),
			'ku'    => __( 'Kurdish', 'wubtitle' ),
			'lt'    => __( 'Lithuanian', 'wubtitle' ),
			'lv'    => __( 'Latvian', 'wubtitle' ),
			'mk'    => __( 'Macedonian (FYROM)', 'wubtitle' ),
			'ml'    => __( 'Malayalam', 'wubtitle' ),
			'ms'    => __( 'Malaysian', 'wubtitle' ),
			'mt'    => __( 'Maltese', 'wubtitle' ),
			'nb'    => __( 'Norwegian (Bokmål)', 'wubtitle' ),
			'nn'    => __( 'Norwegian (Nynorsk)', 'wubtitle' ),
			'no'    => __( 'Norwegian', 'wubtitle' ),
			'pa'    => __( 'Punjabi', 'wubtitle' ),
			'pl'    => __( 'Polish', 'wubtitle' ),
			'pt'    => __( 'Portuguese (Portugal)', 'wubtitle' ),
			'pt-BR' => __( 'Portuguese (Brazil)', 'wubtitle' ),
			'rm'    => __( 'Rhaeto-Romanic', 'wubtitle' ),
			'ro'    => __( 'Romanian', 'wubtitle' ),
			'ro-MD' => __( 'Romanian (Republic of Moldova)', 'wubtitle' ),
			'ru'    => __( 'Russian', 'wubtitle' ),
			'ru-MD' => __( 'Russian (Republic of Moldova)', 'wubtitle' ),
			'sb'    => __( 'Sorbian', 'wubtitle' ),
			'sk'    => __( 'Slovak', 'wubtitle' ),
			'sl'    => __( 'Slovenian', 'wubtitle' ),
			'sr'    => __( 'Serbian', 'wubtitle' ),
			'es'    => __( 'Spanish (Spain)', 'wubtitle' ),
			'es-AR' => __( 'Spanish (Argentina)', 'wubtitle' ),
			'es-BO' => __( 'Spanish (Bolivia)', 'wubtitle' ),
			'es-CL' => __( 'Spanish (Chile)', 'wubtitle' ),
			'es-CO' => __( 'Spanish (Colombia)', 'wubtitle' ),
			'es-CR' => __( 'Spanish (Costa Rica)', 'wubtitle' ),
			'es-DO' => __( 'Spanish (Dominican Republic)', 'wubtitle' ),
			'es-EC' => __( 'Spanish (Ecuador)', 'wubtitle' ),
			'es-GT' => __( 'Spanish (Guatemala)', 'wubtitle' ),
			'es-HN' => __( 'Spanish (Honduras)', 'wubtitle' ),
			'es-MX' => __( 'Spanish (Mexico)', 'wubtitle' ),
			'es-NI' => __( 'Spanish (Nicaragua)', 'wubtitle' ),
			'es-PA' => __( 'Spanish (Panama)', 'wubtitle' ),
			'es-PE' => __( 'Spanish (Peru)', 'wubtitle' ),
			'es-PR' => __( 'Spanish (Puerto Rico)', 'wubtitle' ),
			'es-PY' => __( 'Spanish (Paraguay)', 'wubtitle' ),
			'es-SV' => __( 'Spanish (El Salvador)', 'wubtitle' ),
			'es-UY' => __( 'Spanish (Uruguay)', 'wubtitle' ),
			'es-VE' => __( 'Spanish (Venezuela)', 'wubtitle' ),
			'sv'    => __( 'Swedish', 'wubtitle' ),
			'sv-FI' => __( 'Swedish (Finland)', 'wubtitle' ),
			'th'    => __( 'Thai', 'wubtitle' ),
			'tn'    => __( 'Tswana', 'wubtitle' ),
			'tr'    => __( 'Turkish', 'wubtitle' ),
			'ts'    => __( 'Tsonga', 'wubtitle' ),
			'uk'    => __( 'Ukrainian', 'wubtitle' ),
			'ur'    => __( 'Urdu', 'wubtitle' ),
			've'    => __( 'Venda', 'wubtitle' ),
			'vi'    => __( 'Vietnamese', 'wubtitle' ),
			'cy'    => __( 'Welsh', 'wubtitle' ),
			'xh'    => __( 'Xhosa', 'wubtitle' ),
			'ji'    => __( 'Yiddish', 'wubtitle' ),
			'zu'    => __( 'Zulu', 'wubtitle' ),
		);
		return $languages;
	}
}
